### ISSUE TITLE
There is an issue about the matspec function in mva.plots package.

### ISSUE THREAD

**Issue by wenjun1992** [phenological/mva-plots#22]
I tried to use matspec function from mva.plots package but it failed, see detailed warning below.

matspec(x[1:5,],ppm,roi = c(5.2,5.3))

Error in UseMethod("layout") : 
  no applicable method for 'layout' applied to an object of class "list"

**Comment by 75000089** [comment]
should be resolved with latest update. Please re-do devtools and inform if still having issues
